/*
 * TurmuhrFrame.java
 *
 * Created on 22. April 2003, 18:04
 */

package alpiv.turmuhr;

import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.applet.*;

/**
 *
 * @author  tnfink
 */
class TurmuhrFrame extends javax.swing.JFrame implements Turmuhr
{
    
    private AnalogClock myAnalogClock;    
    private JPanel myClockPanel;
    private Font myStandardFont;

    private static AudioClip myLowBing = 
        Applet.newAudioClip(TurmuhrFrame.class.getResource("/alpiv/turmuhr/sounds/low.au"));
    private static AudioClip myHighBing = 
        Applet.newAudioClip(TurmuhrFrame.class.getResource("/alpiv/turmuhr/sounds/high.au"));
    
    
    /** Creates new form TurmuhrFrame */
    public TurmuhrFrame()
    {
        initComponents();        
        addAnalogClockLabel();        
    }
    
    private void addAnalogClockLabel()
    {
        // size of the clock
        Dimension size = new Dimension(200,200);                
        
        // font of the clock
        myStandardFont = new Font("TimesRoman", Font.BOLD, 10);        
        
        // now create the clock drawer
        myAnalogClock = new AnalogClock(new Rectangle(size.width,size.height));        
        
        // and finally the label
        myClockPanel = new JPanel() {
            public void paint(Graphics gfx)
            {                
                gfx.setFont(myStandardFont);
                myAnalogClock.draw(gfx);                
            }            
        };
        myClockPanel.setMinimumSize(size);
        myClockPanel.setPreferredSize(size);
        myClockPanel.setMaximumSize(size);        
        this.getContentPane().add(myClockPanel,BorderLayout.CENTER);
        
        // pack again...
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */    
    private void initComponents()//GEN-BEGIN:initComponents
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Turmuhr");
        setName("Turmuhr");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt)
    {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new TurmuhrFrame().show();
    }
    
    public void highBell()
    {
        myHighBing.play();
    }    
    
    public void lowBell()
    {
        myLowBing.play();
    }
    
    public void setTime(int hour, int min, int sec)
    {
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR, hour);
        cal.set(Calendar.MINUTE, min);
        cal.set(Calendar.SECOND, sec);
        
        Date date = cal.getTime();
        myAnalogClock.setDate(date);
        //System.out.println("set date to "+date);
        SwingUtilities.invokeLater(new Runnable() {
            public void run()
            {
                myClockPanel.repaint();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
